### ISSUE TITLE
Feature Request:  Timestamps for each line?

### ISSUE THREAD

**Issue by ghost** [Jessecar96/hangouts-reader#2]
It would be very nice to have a timestamp for each line.  yyyy-mm-dd hh:mm:ss would be preferred format since it sorts nicely, but I'd take whatever I can get. :-)

Not an issue, but a feature request... forgive me if you are not interested.

![image](https://cloud.githubusercontent.com/assets/538387/11879363/7e280d64-a4c0-11e5-9b08-9e28c524a1a5.png)

**Comment by juicebyjustin** [comment]
This guy made the change: https://github.com/mkecskes/hangouts-reader

**Comment by Jessecar96** [comment]
Added in #5
